# basics of deep learning like using Sigmoid,Relu function

In [1]:
import numpy as np

In [2]:
input_data=np.array([2,3])

In [3]:
input_data

array([2, 3])

In [4]:
weights_data={'node0':np.array([1,1]),'node1':np.array([-1,1]),'weight_output':np.array([2,-1])}

In [5]:
weights_data

{'node0': array([1, 1]),
 'node1': array([-1,  1]),
 'weight_output': array([ 2, -1])}

In [6]:
node0_value=(input_data*weights_data['node0']).sum()
node1_value=(input_data*weights_data['node1']).sum()

In [7]:
hidden_layer=np.array([node0_value,node1_value])

In [8]:
hidden_layer

array([5, 1])

In [9]:
output=(hidden_layer*weights_data['weight_output']).sum()

In [10]:
output

9

In [11]:
input=np.array([3,6])

In [16]:
weight={'node0':np.array([1,2]),'node1':np.array([2,1]),'output':[1,2]}
weight

{'node0': array([1, 2]), 'node1': array([2, 1]), 'output': [1, 2]}

In [19]:
node0_value=(input*weight['node0']).sum()
node1_value=(input*weight['node1']).sum()


In [20]:
hidden_layer=np.array([node0_value,node1_value])

In [21]:
hidden_layer

array([15, 12])

In [22]:
op=(hidden_layer*weight['output']).sum()

In [23]:
op

39

In [24]:
def relu(x):
    return max(0,x)

In [27]:
def sigmoid(x):
    if x>0:
        return 0
    if x>=0:
        return 1
        

In [28]:
input_data=np.array([2,3])

In [29]:
weights_data={'node0':np.array([1,1]),'node1':np.array([-1,1]),'weight_output':np.array([2,-1])}

In [30]:
node0_value=(input_data*weights_data['node0']).sum()
node1_value=(input_data*weights_data['node1']).sum()

In [31]:
a=relu(output)
a

9

In [32]:
sigmoid(output)

0